### ISSUE TITLE
Publish package on Hex

### ISSUE THREAD

**Issue by binaryseed** [beam-telemetry/telemetry_metrics#10]
I'd like to depend on this library in my New Relic telemetry handler, is it ready to be published to Hex?

**Comment by arkgil** [comment]
@binaryseed we could publish to Hex if you feel like you really need it, but please be aware that the API may, and probably will, change. 

However, if that's not a huge problem for you, I'd wait a bit with publishing to Hex, until we know that at least basic reporter can be built with the current API.

**Comment by binaryseed** [comment]
I was looking to generate metric some structs so my library can take them in & attach to the relevant events. I can include this via `git` for now

Anything I could do to help? I'm building a New Relic reporter over here: https://github.com/binaryseed/new_relic_ecto/pull/4

**Comment by arkgil** [comment]
@binaryseed it would be great if you could use it as git dep for a while now, thanks!

Regarding help, I think the most valuable thing is feedback - if you feel like something is missing, please open up an issue :)
