### ISSUE TITLE
A request for publishing a new release

### ISSUE THREAD

**Issue by c4710n** [beam-telemetry/telemetry_metrics#108]
Since v0.6.1 (Jul 4, 2021), there are some additional improvements. Among them, commit worth mentioning is:
+ https://github.com/beam-telemetry/telemetry_metrics/pull/107

Maybe, it's time to give it a new release, such as v0.6.2 ?

**Comment by josevalim** [comment]
Done!

**Comment by c4710n** [comment]
Thanks. ❤️
