### ISSUE TITLE
Rethinking the distribution metric

### ISSUE THREAD

**Issue by arkgil** [beam-telemetry/telemetry_metrics#31]
I've been thinking about the distribution metric and how its current definition affects implementation of the reporters. In the docs we say that

> Distribution metric builds a histogram of selected measurement's values. Because of that, it is required that you specify the histograms buckets via :buckets option.

Histograms are fantastic because they allow us to approximate the statistics about the data (like arithmetic mean, percentiles, maximum etc.), and at the same time if we have two instances of the same histogram, we can simply add up the quantities in respective buckets to merge them, and the result is still statistically correct, which becomes useful when we run the same instance 

On the other hand, they have the caveat that we can only approximate these statistics with the precision of histogram buckets. If I set the bucket boundaries to `[0, 100, 200]`, I can only say that e.g. the median lies somewhere between these boundaries.

The other issue is that it's not that widely supported in the monitoring systems out there. Prometheus and OpenCensus implement them, but e.g. StatsD does not. In these cases, the required `:buckets` option on the `distribution/2` is awkward, because it's not ever used!

---

Usually we're not interested in the histogram itself, but the properties but can be computed using it, although using histogram for that brings some additional benefits. Thus, I was wondering if we shouldn't change the `distribution/2` metric's definition or behaviour. I was thinking about three possibilities:

1. We change the definition of distribution metric and say that it should allow to explore some statistics about the measurements. We drop the `:buckets` option from Telemetry.Metrics, because the statistics can be computed without the histogram. However, we would need a way to pass additional options to metric definitions, so that `:buckets` can be used when reporters require them (although I think we should do that anyway for other reasons).

2. We add a new metric definition, called e.g. `statistics`, which should allow to view the statistics, and we say that distribution is just a histogram of measurements. This is the approach taken by Prometheus, so that one of these metric types can be used when it makes most sense (e.g. the histogram when you run multiple instances of the same service).

3. We drop the distribution completely, and we define new metric types for some of the statistics, e.g. `mean/2` or `percentile/2`. This idea comes from an observation that all the other metric types define some aggregations of the measurements. Arithmetic mean or percentiles are just another way to aggregate some values in the time window.

If we go for 1., then the meaning of "distribution" will be probably different for each reporter we build. If we go for 2., then we have nice and clear definition for "distribution", and "statistics" becomes a catch-all metric type for all the other aggregations. While 3. can be probably implemented efficiently by the reporters, this may lead users to building many metric definitions, while at least a few monitoring systems calculate a bunch of these statistics at the same time (e.g. in StatsD the "timing" metric calculates percentiles, count, mean, median etc.).

/cc @josevalim @bryannaegele @binaryseed @tsloughter

**Comment by josevalim** [comment]
I am fine if our definition is broad but depending on the backend you need to attach extra information. For example, distribution may not require a buckets, but if you are using the OpenCensus reporter, it can log that this information is missing. Similarly, if Prometheus needs to be told exactly which statistics to use, it can require so.

So I guess I am advocating for 1? We can have a `options` field in distribution and any key given to `distribution` that is not known automatically makes it to `options`.

**Comment by arkgil** [comment]
@josevalim great, I'm all for adding extra options to metrics. I would go one step further and add them to all metric types, e.g. it could be useful for sampling rate in StatsD reporter.

But I'm still not sure about having only distribution type. I think we could promote the usage of histograms by having a dedicated metric type for them, for which the buckets would be required, and have a "statistics" metric as a catch-all type for quantiles, mean, etc.

**Comment by josevalim** [comment]
So I guess the question is: what is the difference between distribution and statistics for the several possible reporters? Which ones would use what?

**Comment by arkgil** [comment]
StatsD would use statistics, on histogram it could log a warning that histograms should be configured on the StatsD daemon side.

Prometheus would use both, since it has a separate metric for a histogram.

OpenCensus would use only the histogram.

When it comes to time-series DBs, they could provide whatever is allowed by the query language. For example, InfluxDB would allow both statistics and the histogram.

**Comment by josevalim** [comment]
Sounds good to me. Let's see what others have to say!

**Comment by binaryseed** [comment]
At New Relic we are working on defining a new generation of metric types, and we have a one similar metric type `summary` = sum, count, min, max. It's about the simplest statistic you could come up with.

We will likely eventually have a histogram metric, but we have never had a histogram or percentile metric before. We support generating a histogram / percentile at query time for data that we sample in un-aggregated form (we ingest both aggregated metrics and raw discrete events).

**Comment by arkgil** [comment]
@binaryseed so it means that breaking current distribution into "statistics" and histogram would be in line with what you're doing at New Relic, correct?

**Comment by binaryseed** [comment]
I think so!

**Comment by arkgil** [comment]
@tsloughter any thoughts on this from your perspective?

@jeffkreeftmeijer I'd love to hear if it's at least a bit consistent with metric types available in AppSignal.

**Comment by tsloughter** [comment]
@arkgil na, nothing from me, sounds fine. @deadtrickster might.

**Comment by deadtrickster** [comment]
We have Summary-like aggregation in opencensus - https://github.com/census-instrumentation/opencensus-erlang/blob/master/src/oc_stat_aggregation_sum.erl

Important property of histograms - they are aggregatable across services, Precomputed statistics isn't. So I think options 2) is the way to go.

**Comment by jeffkreeftmeijer** [comment]
Hey @arkgil, thanks for mentioning me for this issue.

We support distributions/quantiles in our integration and protocol through [measurements](https://docs.appsignal.com/metrics/custom.html#measurement). From these measurements we calculate mean/count and a number of percentiles. The aggregation is done in our agent right now, so our integration only sends measurements to it. We don't currently support histograms right now.

While we have no plans to do so right now, we might switch to using telemetry_metrics down the line and add a way to send already-aggregated data to our agent. Option #2 sounds like it'd make the most sense for us in that case.

**Comment by arkgil** [comment]
@jeffkreeftmeijer thanks for your input, I'm glad to hear that! :) 

BTW, your agent would still be needed, since Telemetry.Metrics doesn't aggregates metrics. It only defines a contract for different metric types, e.g. if the user defines a `counter` metric based on some event, they can provide that definition to StatsD reporter and have it aggregated there, or they could provide it to AppSignal reporter and have the metric published to your service. I think the whole concept is explained better in our [docs](https://hexdocs.pm/telemetry_metrics/overview.html), though :)

**Comment by arkgil** [comment]
#32 adds a a new `summary` metric type.

**Comment by arkgil** [comment]
I started the follow up discussion on extra metric options in #33 .
