### ISSUE TITLE
Include a Telemetry.Metrics.ConsoleReporter

### ISSUE THREAD

**Issue by josevalim** [beam-telemetry/telemetry_metrics#36]
This could be a good debug tool that basically prints the events as they come. For example, in my app I know there is "vm.memory", but I don't know the keys, metadata and so on. The goal of the console reporter is to show what is being consumed and what isn't.

It can also work as a good example for other reporters.

Thoughts?

**Comment by arkgil** [comment]
I like the idea with the built-in tool for inspecting events! But what do you think about including it in the core? Real Telemetry.Metrics reporter is all about aggregations, and not individual events. By including it in the core, we could also make it available to the audience which doesn't use Metrics at all, e.g. Erlang users.

**Comment by josevalim** [comment]
My concern about adding it to core is that we would need a specification of
which events to consume, which we already have here.

Perhaps we could use both, where here we focus on metrics and for core I
would say the best implementation would use tracing.


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by arkgil** [comment]
Yes, I'm all for having a debug/console reporter here as well. As for the core, we even have an issue for that: beam-telemetry/telemetry#12!

**Comment by josevalim** [comment]
PR sent: #37.
