### ISSUE TITLE
Optional distribution buckets

### ISSUE THREAD

**Issue by arkgil** [beam-telemetry/telemetry_metrics#60]
Currently the `:buckets` option for distribution is mandatory - distribution without defined bucket bounds doesn't make much sense. However, in some systems, the buckets are not configured on the reporter side, but on the collector (e.g. vanilla StatsD, DataDog).

I wanted to start a discussion and hear folks' opinions on dropping the requirement of `:buckets` option. If the buckets are required by the reporter, they could be passed as reporter options - we could even push the format we currently have for buckets (i.e. a list or a tuple of start, stop, and step) in the "Writing reporters" guidelines.

**Comment by josevalim** [comment]
Yup, sounds good to me. Let's just remove it and the reporter can warn and use some default buckets if they are required.
