### ISSUE TITLE
Unnecessary option duplicates working with tags and tag_value

### ISSUE THREAD

**Issue by seivan** [beam-telemetry/telemetry_metrics#66]
I noticed this [discussion/pr](https://github.com/beam-telemetry/telemetry_metrics/pull/26) tackled most of it and added a significant improvement, but I feel like it didn't go far enough. 
I ran the unit tests to confirm an idea I had, but I could still be wrong so feel free to close this ticket if I have misunderstood. 

As it is now `tags` on its own will pick out values from the meta data without any transform applied with a `tag_values/1`

So 
```elixir
meta_data = %{foo: :bar}
tags: [:foo]
#results in 
%{:foo: :bar} 
```

But if you supply a transform with `tag_values/1`, whatever the output of that function is, it needs to contain whatever value is part of `tags`

So this would error/warn:

```elixir
meta_data = %{foo: :bar}
tags: [:foo]
tag_values: fn
  %{foo: :bar} -> %{bar: :baz}
end,
#results in  
%{} #
``` 

So my question is, why not combine `tags:` and `tag_values:` into a single option or at least only require one of them to be defined. 

#### As a list
```elixir
meta_data = %{foo: :bar, :baz: 1}
tags: [:foo, :baz]
#results in 
%{:foo: :bar, :baz: 1} 
```

#### As a function

```elixir
meta_data = %{foo: :bar}
tag_values: fn
  %{foo: :bar} -> %{baz: :bar}
  %{baz: :bar} -> %{foo: :bar}
  _ ->.                    %{}
end,
#results in 
%{baz: :bar}
```

This is the part i don't quite understand, if I am defining the tags as part of my function return, why do I need to duplicate them as part of the tags list? 

Unless I've missed something critical, it seems redundant to have to define what portion of the meta data you want twice.

**Comment by josevalim** [comment]
The reason is because some reporters need to declare the metrics shape upfront and, when doing so, we also need to declare the tags, before we consume any measurement.

**Comment by seivan** [comment]
Thanks for clearing that up! 
Edit: Though an argument could be made that making it into one option is breaking that. But making use of one or the other could be beneficial for those who don't have that issue. Defining the keys for the data returning twice seems like something that could be error prone.
