### ISSUE TITLE
0.5.0 is a breaking change

### ISSUE THREAD

**Issue by isaacsanders** [beam-telemetry/telemetry_metrics#74]
Hey all,

One of my colleagues noticed that `buckets` was no longer part of Distribution in 0.5.0.

That is a breaking change. I would ask that 0.5.0 is retired and pulled and you call it 1.0.0, so that we can keep the version as a sem-ver.

**Comment by isaacsanders** [comment]
I read https://semver.org again.

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.


I wish you wouldn't disregard, but I can't stop you.

**Comment by josevalim** [comment]
We haven't released v1.0.0 exactly because the API is not stable yet. We try to minimize breaking changes but the lib is still evolving.
