### ISSUE TITLE
Needs tag for v0.5.0 release

### ISSUE THREAD

**Issue by aaronrenner** [beam-telemetry/telemetry_metrics#75]
When I click on the "View Source" button in hexdocs it tries to take me to a non-existent URL: https://github.com/beam-telemetry/telemetry_metrics/blob/v0.5.0/lib/telemetry_metrics.ex#L1

It appears the problem is the v0.5.0 release hasn't been tagged in the repo.

**Comment by bryannaegele** [comment]
Done!
