### ISSUE TITLE
Is there a clean way to specify tag from nested map metadata?

### ISSUE THREAD

**Issue by en30** [beam-telemetry/telemetry_metrics#79]
For example if I want to add a tag value from `metadata.socket.view` of [Phoenix LiveView's telemetry](https://hexdocs.pm/phoenix_live_view/telemetry.html),
I can achieve it by using `:tags` and `:tag_values` option as below.
```ex
  def metrics() do
    [
      # ...
      counter(
        "phoenix.live_view.mount.start.system_time",
        tag_values: &live_view_tags/1,
        tags: [:view]
      )
    ]
  end

  defp live_view_tags(metadata = %{socket: %{view: view}}) do
    metadata
    |> Map.merge(%{ view: view })
  end
```

Can I write more cleanly like using only `:tags` option?

**Comment by josevalim** [comment]
Unfortunately No. The reason it is done in two distinct steps is because some reporters require the tags to be declared upfront, so you always need both.

**Comment by en30** [comment]
For example, is `tags: [socket: :view]` not regarded as upfront declaration?
I am not sure this is Elixir way because I am new to Elixir.

Anyway there is a way to achieve, so now I am thinking this issue is really minor.
Thank you very much for your time.
