### ISSUE TITLE
Exemplars

### ISSUE THREAD

**Issue by isaacsanders** [beam-telemetry/telemetry_metrics#96]
I'm thinking about exemplars lately. If the set of labels that generate exemplars is just another list in the `reporter_opts`, this library doesn't need to change.

Are there any thoughts on that?

**Comment by josevalim** [comment]
>  If the set of labels that generate exemplars is just another list in the reporter_opts, this library doesn't need to change.

It sounds like this is the way to go?

**Comment by arkgil** [comment]
Yeah, that sounds like the right approach.

**Comment by isaacsanders** [comment]
Here is a PR that implements exemplars for Prometheus: https://github.com/beam-telemetry/telemetry_metrics_prometheus_core/pull/54

**Comment by isaacsanders** [comment]
@josevalim Can you point to there this was completed?

**Comment by josevalim** [comment]
It is not an issue with this library. It goes to reporter_options, as you have described. I guess I could have used the other close command, I am still getting used to that. :)
