### ISSUE TITLE
Missing tag in GitHub for `0.6.1`

### ISSUE THREAD

**Issue by tmr08c** [beam-telemetry/telemetry_metrics#97]
This is similar to #75, but for the latest version. 

The latest version shown on HexDocs is `0.6.1`: https://hexdocs.pm/telemetry_metrics/0.6.1/Telemetry.Metrics.html.

Because there is [no tag for `0.6.1`](https://github.com/beam-telemetry/telemetry_metrics/tags) any "View Source" links do not work ([example](https://github.com/beam-telemetry/telemetry_metrics/blob/v0.6.1/lib/telemetry_metrics.ex#L1)).

**Comment by josevalim** [comment]
Done, thanks!
